### ISSUE TITLE
プラグイン毎にロガーレベルを変更する設定があると便利そう

### ISSUE THREAD

**Issue by Necnion8** [Necnion8/dnCoreV6#6]
プラグイン名だけでなく、ロガー名でも変更できる設定だといいかも。

## イメージ
```yml
loglevel:
  dncore.extensions.musicengine: warning  # = 'file: warning; print: warning'
  dncore.extensions.developtest:
    file: info
    print: debug
```
